name: Terraform Deployment to Azure

#TODO: continue-on-error to be removed when real login values are used

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - Test
          - Prod
      
jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    
    steps:
    - name: Checkout code
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
      
    - name: Set up Terraform
      # https://github.com/hashicorp/setup-terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Azure
      # https://github.com/Azure/login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      continue-on-error: true
              
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
      continue-on-error: true

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      # https://spacelift.io/blog/terraform-tfvars
      run: terraform plan -var-file="${{ github.workspace }}/${{ github.event.inputs.env }}.tfvars"
      env:
        # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
    - name: Approve and apply
      if: ${{ github.event_name == 'push' }}
      run: terraform apply -auto-approve -var-file="${{ github.workspace }}/${{ github.event.inputs.env }}.tfvars"
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
