name: Terraform Deployment to Azure

on: workflow_dispatch

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # https://github.com/actions/checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      # https://github.com/hashicorp/setup-terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Azure
      # https://github.com/Azure/login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'Sandbox'
              
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
